server:
  port: "10000"

spring:
  application:
    name: "remind-service"

logging:
  level:
    root: info
    com.xuegao.remind: debug

xuegao:
  concurrent:
    # 开启为true，不开启则设置为false
    enable: "true"
    # 以下都有默认值，可以不设置
    # 线程池核心线程数
    corePoolSize: "16"
    # 线程池最大线程数
    maximumPoolSize: "16"
    # 超过核心线程数的线程的存活时间
    keepAliveTime: "30"
    # 阻塞队列容量
    blockingQueueCapacity: "1024"
    # 阻塞队列类型
    blockingQueueType: "ARRAY_BLOCKING_QUEUE"
    # 是否使用线程池并发执行查询
    concurrentActive: "true"

feign:
  client:
    config:
      #default 设置的全局超时时间
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000

  compression:
    #  Tip提醒： 如果服务消费端的CPU资源比较紧张的话，建议不要开启数据的压缩功能，
    #  因为数据压缩和解压都需要消耗CPU的资源，这样反而会给CPU增加了额外的负担，也会导致系统性能降低。
    request:
      # 开启请求数据的压缩功能
      enabled: true
      mime-types: text/xml,application/xml, application/json  # 压缩类型
      min-request-size: 1024  # 最小压缩值标准，当数据大于 1024 才会进行压缩
    response:
      enabled: true  # 开启响应数据压缩功能


